plugins { id 'com.android.application' }

android {
    namespace 'com.steamhunter.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.steamhunter.app'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
